const languages = {
  "1c enterprise": { name: "1C Enterprise", width: 78, color: "#814ccc" },
  "2-dimensional array": { name: "2-Dimensional Array", width: 117, color: "#38761d" },
  "4d": { name: "4D", width: 17, color: "#004289" },
  abap: { name: "ABAP", width: 35, color: "#e8274b" },
  "abap cds": { name: "ABAP CDS", width: 63, color: "#555e25" },
  "ags script": { name: "AGS Script", width: 65, color: "#b9d9ff" },
  aidl: { name: "AIDL", width: 30, color: "#34eb6b" },
  al: { name: "AL", width: 18, color: "#3aa2b5" },
  ampl: { name: "AMPL", width: 36, color: "#e6efbb" },
  antlr: { name: "ANTLR", width: 42, color: "#9dc3ff" },
  "api blueprint": { name: "API Blueprint", width: 78, color: "#2acca8" },
  apl: { name: "APL", width: 26, color: "#5a8164" },
  "asp.net": { name: "ASP.NET", width: 52, color: "#9400ff" },
  ats: { name: "ATS", width: 24, color: "#1ac620" },
  actionscript: { name: "ActionScript", width: 73, color: "#882b0f" },
  ada: { name: "Ada", width: 24, color: "#02f88c" },
  "adblock filter list": { name: "Adblock Filter List", width: 107, color: "#800000" },
  "adobe font metrics": { name: "Adobe Font Metrics", width: 113, color: "#fa0f00" },
  agda: { name: "Agda", width: 31, color: "#315665" },
  alloy: { name: "Alloy", width: 31, color: "#64c800" },
  "alpine abuild": { name: "Alpine Abuild", width: 78, color: "#0d597f" },
  "altium designer": { name: "Altium Designer", width: 94, color: "#a89663" },
  angelscript: { name: "AngelScript", width: 69, color: "#c7d7dc" },
  "answer set programming": { name: "Answer Set Programming", width: 148, color: "#a9cc29" },
  "ant build system": { name: "Ant Build System", width: 101, color: "#a9157e" },
  antlers: { name: "Antlers", width: 43, color: "#ff269e" },
  apacheconf: { name: "ApacheConf", width: 73, color: "#d12127" },
  apex: { name: "Apex", width: 31, color: "#1797c0" },
  "apollo guidance computer": { name: "Apollo Guidance Computer", width: 158, color: "#0b3d91" },
  applescript: { name: "AppleScript", width: 69, color: "#101f1f" },
  arc: { name: "Arc", width: 21, color: "#aa2afe" },
  asciidoc: { name: "AsciiDoc", width: 53, color: "#73a0c5" },
  aspectj: { name: "AspectJ", width: 48, color: "#a957b0" },
  assembly: { name: "Assembly", width: 58, color: "#6e4c13" },
  astro: { name: "Astro", width: 33, color: "#ff5a03" },
  asymptote: { name: "Asymptote", width: 63, color: "#ff0000" },
  augeas: { name: "Augeas", width: 45, color: "#9cc134" },
  autohotkey: { name: "AutoHotkey", width: 69, color: "#6594b9" },
  autoit: { name: "AutoIt", width: 37, color: "#1c3552" },
  "avro idl": { name: "Avro IDL", width: 51, color: "#0040ff" },
  awk: { name: "Awk", width: 26, color: "#c30e9b" },
  b4x: { name: "B4X", width: 24, color: "#00e4ff" },
  basic: { name: "BASIC", width: 38, color: "#ff0000" },
  bqn: { name: "BQN", width: 27, color: "#2b7067" },
  ballerina: { name: "Ballerina", width: 51, color: "#ff5000" },
  batchfile: { name: "Batchfile", width: 51, color: "#c1f12e" },
  beef: { name: "Beef", width: 27, color: "#a52f4e" },
  berry: { name: "Berry", width: 32, color: "#15a13c" },
  bibtex: { name: "BibTeX", width: 41, color: "#778899" },
  bicep: { name: "Bicep", width: 33, color: "#519aba" },
  bikeshed: { name: "Bikeshed", width: 53, color: "#5562ac" },
  bison: { name: "Bison", width: 33, color: "#6a463f" },
  bitbake: { name: "BitBake", width: 45, color: "#00bce4" },
  blade: { name: "Blade", width: 33, color: "#f7523f" },
  blitzbasic: { name: "BlitzBasic", width: 58, color: "#00ffae" },
  blitzmax: { name: "BlitzMax", width: 49, color: "#cd6400" },
  bluespec: { name: "Bluespec", width: 54, color: "#12223c" },
  "bluespec bh": { name: "Bluespec BH", width: 74, color: "#12223c" },
  boo: { name: "Boo", width: 24, color: "#d4bec1" },
  boogie: { name: "Boogie", width: 41, color: "#c80fa0" },
  brainfuck: { name: "Brainfuck", width: 56, color: "#2f2530" },
  brighterscript: { name: "BrighterScript", width: 82, color: "#66aabb" },
  brightscript: { name: "Brightscript", width: 69, color: "#662d91" },
  browserslist: { name: "Browserslist", width: 73, color: "#ffd539" },
  c: { name: "C", width: 9, color: "#555555" },
  "c#": { name: "C#", width: 16, color: "#178600" },
  "c++": { name: "C++", width: 23, color: "#f34b7d" },
  "cap cds": { name: "CAP CDS", width: 54, color: "#0092d1" },
  clips: { name: "CLIPS", width: 35, color: "#00a300" },
  cmake: { name: "CMake", width: 39, color: "#da3434" },
  collada: { name: "COLLADA", width: 59, color: "#f1a42b" },
  cson: { name: "CSON", width: 35, color: "#244776" },
  css: { name: "CSS", width: 25, color: "#663399" },
  csv: { name: "CSV", width: 26, color: "#237346" },
  cue: { name: "CUE", width: 25, color: "#5886e1" },
  cweb: { name: "CWeb", width: 34, color: "#00007a" },
  "cabal config": { name: "Cabal Config", width: 74, color: "#483465" },
  caddyfile: { name: "Caddyfile", width: 54, color: "#22b638" },
  cadence: { name: "Cadence", width: 50, color: "#00ef8b" },
  cairo: { name: "Cairo", width: 31, color: "#ff4a48" },
  "cairo zero": { name: "Cairo Zero", width: 61, color: "#ff4a48" },
  cameligo: { name: "CameLIGO", width: 63, color: "#3be133" },
  "cap'n proto": { name: "Cap'n Proto", width: 68, color: "#c42727" },
  carbon: { name: "Carbon", width: 42, color: "#222222" },
  ceylon: { name: "Ceylon", width: 40, color: "#dfa535" },
  chapel: { name: "Chapel", width: 40, color: "#8dc63f" },
  chuck: { name: "ChucK", width: 39, color: "#3f8000" },
  circom: { name: "Circom", width: 42, color: "#707575" },
  cirru: { name: "Cirru", width: 29, color: "#ccccff" },
  clarion: { name: "Clarion", width: 41, color: "#db901e" },
  clarity: { name: "Clarity", width: 38, color: "#5546ff" },
  "classic asp": { name: "Classic ASP", width: 70, color: "#6a40fd" },
  clean: { name: "Clean", width: 33, color: "#3f85af" },
  click: { name: "Click", width: 29, color: "#e4e6f3" },
  clojure: { name: "Clojure", width: 42, color: "#db5855" },
  "closure templates": { name: "Closure Templates", width: 107, color: "#0d948f" },
  "cloud firestore security rules": {
    name: "Cloud Firestore Security Rules",
    width: 176,
    color: "#ffa000",
  },
  codeql: { name: "CodeQL", width: 47, color: "#140f46" },
  coffeescript: { name: "CoffeeScript", width: 72, color: "#244776" },
  coldfusion: { name: "ColdFusion", width: 66, color: "#ed2cd6" },
  "coldfusion cfc": { name: "ColdFusion CFC", width: 94, color: "#ed2cd6" },
  "common lisp": { name: "Common Lisp", width: 81, color: "#3fb68b" },
  "common workflow language": { name: "Common Workflow Language", width: 169, color: "#b5314c" },
  "component pascal": { name: "Component Pascal", width: 108, color: "#b0ce4e" },
  coq: { name: "Coq", width: 23, color: "#d0b68c" },
  crystal: { name: "Crystal", width: 41, color: "#000100" },
  csound: { name: "Csound", width: 45, color: "#1a1a1a" },
  "csound document": { name: "Csound Document", width: 108, color: "#1a1a1a" },
  "csound score": { name: "Csound Score", width: 82, color: "#1a1a1a" },
  cuda: { name: "Cuda", width: 30, color: "#3a4e3a" },
  curry: { name: "Curry", width: 32, color: "#531242" },
  cylc: { name: "Cylc", width: 26, color: "#00b3fd" },
  cypher: { name: "Cypher", width: 43, color: "#34c0eb" },
  cython: { name: "Cython", width: 41, color: "#fedf5b" },
  d: { name: "D", width: 9, color: "#ba595e" },
  d2: { name: "D2", width: 16, color: "#526ee8" },
  dm: { name: "DM", width: 19, color: "#447265" },
  dafny: { name: "Dafny", width: 34, color: "#ffec25" },
  "darcs patch": { name: "Darcs Patch", width: 69, color: "#8eff23" },
  dart: { name: "Dart", width: 25, color: "#00b4ab" },
  dataweave: { name: "DataWeave", width: 64, color: "#003a52" },
  "debian package control file": {
    name: "Debian Package Control File",
    width: 162,
    color: "#d70751",
  },
  denizenscript: { name: "DenizenScript", width: 81, color: "#fbee96" },
  dhall: { name: "Dhall", width: 29, color: "#dfafff" },
  "directx 3d file": { name: "DirectX 3D File", width: 85, color: "#aace60" },
  dockerfile: { name: "Dockerfile", width: 58, color: "#384d54" },
  dogescript: { name: "Dogescript", width: 64, color: "#cca760" },
  dotenv: { name: "Dotenv", width: 41, color: "#e5d559" },
  dune: { name: "Dune", width: 30, color: "#89421e" },
  dylan: { name: "Dylan", width: 33, color: "#6c616e" },
  e: { name: "E", width: 8, color: "#ccce35" },
  ecl: { name: "ECL", width: 25, color: "#8a1267" },
  eclipse: { name: "ECLiPSe", width: 50, color: "#001d9d" },
  ejs: { name: "EJS", width: 23, color: "#a91e50" },
  eq: { name: "EQ", width: 18, color: "#a78649" },
  earthly: { name: "Earthly", width: 41, color: "#2af0ff" },
  easybuild: { name: "Easybuild", width: 57, color: "#069406" },
  "ecere projects": { name: "Ecere Projects", width: 84, color: "#913960" },
  ecmarkup: { name: "Ecmarkup", width: 59, color: "#eb8131" },
  edge: { name: "Edge", width: 30, color: "#0dffe0" },
  edgeql: { name: "EdgeQL", width: 47, color: "#31a7ff" },
  editorconfig: { name: "EditorConfig", width: 73, color: "#fff1f2" },
  eiffel: { name: "Eiffel", width: 29, color: "#4d6977" },
  elixir: { name: "Elixir", width: 31, color: "#6e4a7e" },
  elm: { name: "Elm", width: 22, color: "#60b5cc" },
  elvish: { name: "Elvish", width: 35, color: "#55bb55" },
  "elvish transcript": { name: "Elvish Transcript", width: 98, color: "#55bb55" },
  "emacs lisp": { name: "Emacs Lisp", width: 67, color: "#c065db" },
  emberscript: { name: "EmberScript", width: 72, color: "#fff4f3" },
  erlang: { name: "Erlang", width: 37, color: "#b83998" },
  euphoria: { name: "Euphoria", width: 52, color: "#ff790b" },
  "f#": { name: "F#", width: 14, color: "#b845fc" },
  "f*": { name: "F*", width: 12, color: "#572e30" },
  "figlet font": { name: "FIGlet Font", width: 64, color: "#ffddbb" },
  firrtl: { name: "FIRRTL", width: 43, color: "#2f632f" },
  flux: { name: "FLUX", width: 32, color: "#88ccff" },
  factor: { name: "Factor", width: 38, color: "#636746" },
  fancy: { name: "Fancy", width: 35, color: "#7b9db4" },
  fantom: { name: "Fantom", width: 44, color: "#14253c" },
  faust: { name: "Faust", width: 33, color: "#c37240" },
  fennel: { name: "Fennel", width: 39, color: "#fff3d7" },
  "filebench wml": { name: "Filebench WML", width: 89, color: "#f6b900" },
  fluent: { name: "Fluent", width: 37, color: "#ffcc33" },
  forth: { name: "Forth", width: 31, color: "#341708" },
  fortran: { name: "Fortran", width: 42, color: "#4d41b1" },
  "fortran free form": { name: "Fortran Free Form", width: 104, color: "#4d41b1" },
  freebasic: { name: "FreeBASIC", width: 63, color: "#141ac9" },
  freemarker: { name: "FreeMarker", width: 66, color: "#0050b2" },
  frege: { name: "Frege", width: 33, color: "#00cafe" },
  futhark: { name: "Futhark", width: 44, color: "#5f021f" },
  "g-code": { name: "G-code", width: 42, color: "#d08cf2" },
  gaml: { name: "GAML", width: 36, color: "#ffc766" },
  gams: { name: "GAMS", width: 36, color: "#f49a22" },
  gap: { name: "GAP", width: 26, color: "#0000cc" },
  "gcc machine description": { name: "GCC Machine Description", width: 147, color: "#ffcfab" },
  gdscript: { name: "GDScript", width: 53, color: "#355570" },
  gedcom: { name: "GEDCOM", width: 54, color: "#003058" },
  glsl: { name: "GLSL", width: 33, color: "#5686a5" },
  gsc: { name: "GSC", width: 26, color: "#ff6800" },
  "game maker language": { name: "Game Maker Language", width: 132, color: "#71b417" },
  "gemfile.lock": { name: "Gemfile.lock", width: 72, color: "#701516" },
  gemini: { name: "Gemini", width: 41, color: "#ff6900" },
  "genero 4gl": { name: "Genero 4gl", width: 63, color: "#63408e" },
  "genero per": { name: "Genero per", width: 65, color: "#d8df39" },
  genie: { name: "Genie", width: 34, color: "#fb855d" },
  genshi: { name: "Genshi", width: 41, color: "#951531" },
  "gentoo ebuild": { name: "Gentoo Ebuild", width: 82, color: "#9400ff" },
  "gentoo eclass": { name: "Gentoo Eclass", width: 84, color: "#9400ff" },
  "gerber image": { name: "Gerber Image", width: 78, color: "#d20b00" },
  gherkin: { name: "Gherkin", width: 45, color: "#5b2063" },
  "git attributes": { name: "Git Attributes", width: 77, color: "#f44d27" },
  "git config": { name: "Git Config", width: 58, color: "#f44d27" },
  "git revision list": { name: "Git Revision List", width: 96, color: "#f44d27" },
  gleam: { name: "Gleam", width: 37, color: "#ffaff3" },
  "glimmer js": { name: "Glimmer JS", width: 67, color: "#f5835f" },
  "glimmer ts": { name: "Glimmer TS", width: 67, color: "#3178c6" },
  glyph: { name: "Glyph", width: 34, color: "#c1ac7f" },
  gnuplot: { name: "Gnuplot", width: 47, color: "#f0a9f0" },
  go: { name: "Go", width: 17, color: "#00add8" },
  "go checksums": { name: "Go Checksums", width: 88, color: "#00add8" },
  "go module": { name: "Go Module", width: 62, color: "#00add8" },
  "go workspace": { name: "Go Workspace", width: 84, color: "#00add8" },
  "godot resource": { name: "Godot Resource", width: 94, color: "#355570" },
  golo: { name: "Golo", width: 28, color: "#88562a" },
  gosu: { name: "Gosu", width: 31, color: "#82937f" },
  grace: { name: "Grace", width: 34, color: "#615f8b" },
  gradle: { name: "Gradle", width: 38, color: "#02303a" },
  "gradle kotlin dsl": { name: "Gradle Kotlin DSL", width: 103, color: "#02303a" },
  "grammatical framework": { name: "Grammatical Framework", width: 140, color: "#ff0000" },
  graphql: { name: "GraphQL", width: 53, color: "#e10098" },
  "graphviz (dot)": { name: "Graphviz (DOT)", width: 88, color: "#2596be" },
  groovy: { name: "Groovy", width: 42, color: "#4298b8" },
  "groovy server pages": { name: "Groovy Server Pages", width: 122, color: "#4298b8" },
  haproxy: { name: "HAProxy", width: 51, color: "#106da9" },
  hcl: { name: "HCL", width: 25, color: "#844fba" },
  hlsl: { name: "HLSL", width: 32, color: "#aace60" },
  hocon: { name: "HOCON", width: 45, color: "#9ff8ee" },
  html: { name: "HTML", width: 34, color: "#e34c26" },
  "html+ecr": { name: "HTML+ECR", width: 66, color: "#2e1052" },
  "html+eex": { name: "HTML+EEX", width: 65, color: "#6e4a7e" },
  "html+erb": { name: "HTML+ERB", width: 66, color: "#701516" },
  "html+php": { name: "HTML+PHP", width: 65, color: "#4f5d95" },
  "html+razor": { name: "HTML+Razor", width: 75, color: "#512be4" },
  http: { name: "HTTP", width: 31, color: "#005c9c" },
  hxml: { name: "HXML", width: 35, color: "#f68712" },
  hack: { name: "Hack", width: 29, color: "#878787" },
  haml: { name: "Haml", width: 29, color: "#ece2a9" },
  handlebars: { name: "Handlebars", width: 66, color: "#f7931e" },
  harbour: { name: "Harbour", width: 48, color: "#0e60e3" },
  hare: { name: "Hare", width: 27, color: "#9d7424" },
  haskell: { name: "Haskell", width: 42, color: "#5e5086" },
  haxe: { name: "Haxe", width: 29, color: "#df7900" },
  hiveql: { name: "HiveQL", width: 43, color: "#dce200" },
  holyc: { name: "HolyC", width: 35, color: "#ffefaf" },
  "hosts file": { name: "Hosts File", width: 58, color: "#308888" },
  hy: { name: "Hy", width: 16, color: "#7790b2" },
  idl: { name: "IDL", width: 20, color: "#a3522f" },
  "igor pro": { name: "IGOR Pro", width: 55, color: "#0000cc" },
  ini: { name: "INI", width: 15, color: "#d1dbe0" },
  idris: { name: "Idris", width: 26, color: "#b30000" },
  "ignore list": { name: "Ignore List", width: 62, color: "#000000" },
  "imagej macro": { name: "ImageJ Macro", width: 81, color: "#99aaff" },
  imba: { name: "Imba", width: 28, color: "#16cec6" },
  "inno setup": { name: "Inno Setup", width: 63, color: "#264b99" },
  io: { name: "Io", width: 11, color: "#a9188d" },
  ioke: { name: "Ioke", width: 24, color: "#078193" },
  isabelle: { name: "Isabelle", width: 44, color: "#fefe00" },
  "isabelle root": { name: "Isabelle ROOT", width: 83, color: "#fefe00" },
  j: { name: "J", width: 8, color: "#9eedff" },
  "jar manifest": { name: "JAR Manifest", width: 78, color: "#b07219" },
  jcl: { name: "JCL", width: 24, color: "#d90e09" },
  jflex: { name: "JFlex", width: 32, color: "#dbca00" },
  json: { name: "JSON", width: 34, color: "#292929" },
  "json with comments": { name: "JSON with Comments", width: 127, color: "#292929" },
  json5: { name: "JSON5", width: 41, color: "#267cb9" },
  jsonld: { name: "JSONLD", width: 50, color: "#0c479c" },
  jsoniq: { name: "JSONiq", width: 44, color: "#40d47e" },
  jai: { name: "Jai", width: 18, color: "#ab8b4b" },
  janet: { name: "Janet", width: 33, color: "#0886a5" },
  jasmin: { name: "Jasmin", width: 42, color: "#d03600" },
  java: { name: "Java", width: 28, color: "#b07219" },
  "java properties": { name: "Java Properties", width: 91, color: "#2a6277" },
  "java server pages": { name: "Java Server Pages", width: 107, color: "#2a6277" },
  "java template engine": { name: "Java Template Engine", width: 126, color: "#2a6277" },
  javascript: { name: "JavaScript", width: 63, color: "#f1e05a" },
  "javascript+erb": { name: "JavaScript+ERB", width: 94, color: "#f1e05a" },
  "jest snapshot": { name: "Jest Snapshot", width: 84, color: "#15c213" },
  "jetbrains mps": { name: "JetBrains MPS", width: 85, color: "#21d789" },
  jinja: { name: "Jinja", width: 29, color: "#a52a22" },
  jison: { name: "Jison", width: 32, color: "#56b3cb" },
  "jison lex": { name: "Jison Lex", width: 57, color: "#56b3cb" },
  jolie: { name: "Jolie", width: 29, color: "#843179" },
  jsonnet: { name: "Jsonnet", width: 48, color: "#0064bd" },
  julia: { name: "Julia", width: 29, color: "#a270ba" },
  "julia repl": { name: "Julia REPL", width: 64, color: "#a270ba" },
  "jupyter notebook": { name: "Jupyter Notebook", width: 103, color: "#da5b0b" },
  just: { name: "Just", width: 27, color: "#384d54" },
  kdl: { name: "KDL", width: 25, color: "#ffb3b3" },
  krl: { name: "KRL", width: 25, color: "#28430a" },
  "kaitai struct": { name: "Kaitai Struct", width: 72, color: "#773b37" },
  kakounescript: { name: "KakouneScript", width: 86, color: "#6f8042" },
  kerboscript: { name: "KerboScript", width: 70, color: "#41adf0" },
  "kicad layout": { name: "KiCad Layout", width: 78, color: "#2f4aab" },
  "kicad legacy layout": { name: "KiCad Legacy Layout", width: 123, color: "#2f4aab" },
  "kicad schematic": { name: "KiCad Schematic", width: 98, color: "#2f4aab" },
  kotlin: { name: "Kotlin", width: 34, color: "#a97bff" },
  lfe: { name: "LFE", width: 23, color: "#4c3023" },
  llvm: { name: "LLVM", width: 32, color: "#185619" },
  lolcode: { name: "LOLCODE", width: 59, color: "#cc9900" },
  lsl: { name: "LSL", width: 23, color: "#3d9970" },
  labview: { name: "LabVIEW", width: 53, color: "#fede06" },
  lark: { name: "Lark", width: 26, color: "#2980b9" },
  lasso: { name: "Lasso", width: 35, color: "#999999" },
  latte: { name: "Latte", width: 29, color: "#f2a542" },
  less: { name: "Less", width: 28, color: "#1d365d" },
  lex: { name: "Lex", width: 21, color: "#dbca00" },
  ligolang: { name: "LigoLANG", width: 59, color: "#0e74ff" },
  lilypond: { name: "LilyPond", width: 51, color: "#9ccc7c" },
  liquid: { name: "Liquid", width: 36, color: "#67b8de" },
  "literate agda": { name: "Literate Agda", width: 77, color: "#315665" },
  "literate coffeescript": { name: "Literate CoffeeScript", width: 119, color: "#244776" },
  "literate haskell": { name: "Literate Haskell", width: 89, color: "#5e5086" },
  "livecode script": { name: "LiveCode Script", width: 92, color: "#0c5ba5" },
  livescript: { name: "LiveScript", width: 59, color: "#499886" },
  logtalk: { name: "Logtalk", width: 43, color: "#295b9a" },
  lookml: { name: "LookML", width: 47, color: "#652b81" },
  lua: { name: "Lua", width: 22, color: "#000080" },
  luau: { name: "Luau", width: 29, color: "#00a2ff" },
  matlab: { name: "MATLAB", width: 50, color: "#e16737" },
  maxscript: { name: "MAXScript", width: 62, color: "#00a6a6" },
  mdx: { name: "MDX", width: 28, color: "#fcb32c" },
  mlir: { name: "MLIR", width: 30, color: "#5ec8db" },
  mql4: { name: "MQL4", width: 34, color: "#62a8d6" },
  mql5: { name: "MQL5", width: 34, color: "#4a76b8" },
  mtml: { name: "MTML", width: 35, color: "#b7e1f4" },
  macaulay2: { name: "Macaulay2", width: 61, color: "#d8ffff" },
  makefile: { name: "Makefile", width: 48, color: "#427819" },
  mako: { name: "Mako", width: 31, color: "#7e858d" },
  markdown: { name: "Markdown", width: 59, color: "#083fa1" },
  marko: { name: "Marko", width: 36, color: "#42bff2" },
  mask: { name: "Mask", width: 30, color: "#f97732" },
  mathematica: { name: "Mathematica", width: 73, color: "#dd1100" },
  max: { name: "Max", width: 24, color: "#c4a79c" },
  mercury: { name: "Mercury", width: 47, color: "#ff2b2b" },
  mermaid: { name: "Mermaid", width: 49, color: "#ff3670" },
  meson: { name: "Meson", width: 38, color: "#007800" },
  metal: { name: "Metal", width: 31, color: "#8f14e9" },
  miniyaml: { name: "MiniYAML", width: 58, color: "#ff1111" },
  minizinc: { name: "MiniZinc", width: 49, color: "#06a9e6" },
  mint: { name: "Mint", width: 26, color: "#02b046" },
  mirah: { name: "Mirah", width: 32, color: "#c7a938" },
  modelica: { name: "Modelica", width: 52, color: "#de1d31" },
  "modula-2": { name: "Modula-2", width: 53, color: "#10253f" },
  "modula-3": { name: "Modula-3", width: 53, color: "#223388" },
  mojo: { name: "Mojo", width: 29, color: "#ff4c1f" },
  "monkey c": { name: "Monkey C", width: 57, color: "#8d6747" },
  moonbit: { name: "MoonBit", width: 49, color: "#b92381" },
  moonscript: { name: "MoonScript", width: 67, color: "#ff4585" },
  motoko: { name: "Motoko", width: 43, color: "#fbb03b" },
  "motorola 68k assembly": { name: "Motorola 68K Assembly", width: 136, color: "#005daa" },
  move: { name: "Move", width: 31, color: "#4a137a" },
  mustache: { name: "Mustache", width: 56, color: "#724b3b" },
  ncl: { name: "NCL", width: 25, color: "#28431f" },
  nmodl: { name: "NMODL", width: 45, color: "#00356b" },
  "npm config": { name: "NPM Config", width: 68, color: "#cb3837" },
  nwscript: { name: "NWScript", width: 55, color: "#111522" },
  nasal: { name: "Nasal", width: 32, color: "#1d2c4e" },
  nearley: { name: "Nearley", width: 44, color: "#990000" },
  nemerle: { name: "Nemerle", width: 48, color: "#3d3c6e" },
  netlinx: { name: "NetLinx", width: 44, color: "#0aa0ff" },
  "netlinx+erb": { name: "NetLinx+ERB", width: 77, color: "#747faa" },
  netlogo: { name: "NetLogo", width: 49, color: "#ff6375" },
  newlisp: { name: "NewLisp", width: 50, color: "#87aed7" },
  nextflow: { name: "Nextflow", width: 51, color: "#3ac486" },
  nginx: { name: "Nginx", width: 34, color: "#009639" },
  nim: { name: "Nim", width: 23, color: "#ffc200" },
  nit: { name: "Nit", width: 17, color: "#009917" },
  nix: { name: "Nix", width: 19, color: "#7e7eff" },
  noir: { name: "Noir", width: 25, color: "#2f1f49" },
  nu: { name: "Nu", width: 16, color: "#c9df40" },
  numpy: { name: "NumPy", width: 42, color: "#9c8af9" },
  nunjucks: { name: "Nunjucks", width: 54, color: "#3d8137" },
  nushell: { name: "Nushell", width: 43, color: "#4e9906" },
  "oasv2-json": { name: "OASv2-json", width: 68, color: "#85ea2d" },
  "oasv2-yaml": { name: "OASv2-yaml", width: 71, color: "#85ea2d" },
  "oasv3-json": { name: "OASv3-json", width: 68, color: "#85ea2d" },
  "oasv3-yaml": { name: "OASv3-yaml", width: 71, color: "#85ea2d" },
  ocaml: { name: "OCaml", width: 39, color: "#ef7a08" },
  "omnet++ msg": { name: "OMNeT++ MSG", width: 87, color: "#a0e0a0" },
  "omnet++ ned": { name: "OMNeT++ NED", width: 85, color: "#08607c" },
  objectscript: { name: "ObjectScript", width: 72, color: "#424893" },
  "objective-c": { name: "Objective-C", width: 67, color: "#438eff" },
  "objective-c++": { name: "Objective-C++", width: 81, color: "#6866fb" },
  "objective-j": { name: "Objective-J", width: 65, color: "#ff0c5a" },
  odin: { name: "Odin", width: 27, color: "#60affe" },
  omgrofl: { name: "Omgrofl", width: 47, color: "#cabbff" },
  opal: { name: "Opal", width: 27, color: "#f7ede0" },
  "open policy agent": { name: "Open Policy Agent", width: 107, color: "#7d9199" },
  "openapi specification v2": { name: "OpenAPI Specification v2", width: 146, color: "#85ea2d" },
  "openapi specification v3": { name: "OpenAPI Specification v3", width: 146, color: "#85ea2d" },
  opencl: { name: "OpenCL", width: 47, color: "#ed2e2d" },
  "openedge abl": { name: "OpenEdge ABL", width: 88, color: "#5ce600" },
  openqasm: { name: "OpenQASM", width: 67, color: "#aa70ff" },
  openscad: { name: "OpenSCAD", width: 65, color: "#e5cd45" },
  "option list": { name: "Option List", width: 64, color: "#476732" },
  org: { name: "Org", width: 21, color: "#77aa99" },
  overpassql: { name: "OverpassQL", width: 72, color: "#cce2aa" },
  oxygene: { name: "Oxygene", width: 51, color: "#cdd0e3" },
  oz: { name: "Oz", width: 16, color: "#fab738" },
  p4: { name: "P4", width: 15, color: "#7055b5" },
  pddl: { name: "PDDL", width: 33, color: "#0d00ff" },
  "peg.js": { name: "PEG.js", width: 39, color: "#234d6b" },
  php: { name: "PHP", width: 25, color: "#4f5d95" },
  plsql: { name: "PLSQL", width: 41, color: "#dad8d8" },
  plpgsql: { name: "PLpgSQL", width: 55, color: "#336790" },
  "pov-ray sdl": { name: "POV-Ray SDL", width: 79, color: "#6bac65" },
  pact: { name: "Pact", width: 26, color: "#f7a8b8" },
  pan: { name: "Pan", width: 22, color: "#cc0000" },
  papyrus: { name: "Papyrus", width: 48, color: "#6600cc" },
  parrot: { name: "Parrot", width: 36, color: "#f3ca0a" },
  pascal: { name: "Pascal", width: 38, color: "#e3f171" },
  pawn: { name: "Pawn", width: 31, color: "#dbb284" },
  pep8: { name: "Pep8", width: 29, color: "#c76f5b" },
  perl: { name: "Perl", width: 23, color: "#0298c3" },
  picolisp: { name: "PicoLisp", width: 51, color: "#6067af" },
  piglatin: { name: "PigLatin", width: 47, color: "#fcd7de" },
  pike: { name: "Pike", width: 25, color: "#005390" },
  "pip requirements": { name: "Pip Requirements", width: 102, color: "#ffd343" },
  pkl: { name: "Pkl", width: 18, color: "#6b9543" },
  plantuml: { name: "PlantUML", width: 56, color: "#fbbd16" },
  pogoscript: { name: "PogoScript", width: 65, color: "#d80074" },
  polar: { name: "Polar", width: 31, color: "#ae81ff" },
  portugol: { name: "Portugol", width: 49, color: "#f8bd00" },
  postcss: { name: "PostCSS", width: 51, color: "#dc3a0c" },
  postscript: { name: "PostScript", width: 61, color: "#da291c" },
  powerbuilder: { name: "PowerBuilder", width: 79, color: "#8f0f8d" },
  powershell: { name: "PowerShell", width: 65, color: "#012456" },
  praat: { name: "Praat", width: 31, color: "#c8506d" },
  prisma: { name: "Prisma", width: 40, color: "#0c344b" },
  processing: { name: "Processing", width: 65, color: "#0096d8" },
  procfile: { name: "Procfile", width: 44, color: "#3b2f63" },
  prolog: { name: "Prolog", width: 38, color: "#74283c" },
  promela: { name: "Promela", width: 48, color: "#de0000" },
  "propeller spin": { name: "Propeller Spin", width: 81, color: "#7fa2a7" },
  pug: { name: "Pug", width: 23, color: "#a86454" },
  puppet: { name: "Puppet", width: 42, color: "#302b6d" },
  purebasic: { name: "PureBasic", width: 59, color: "#5a6986" },
  purescript: { name: "PureScript", width: 62, color: "#1d222d" },
  pyret: { name: "Pyret", width: 31, color: "#ee1e10" },
  python: { name: "Python", width: 41, color: "#3572a5" },
  "python console": { name: "Python console", width: 90, color: "#3572a5" },
  "python traceback": { name: "Python traceback", width: 100, color: "#3572a5" },
  "q#": { name: "Q#", width: 16, color: "#fed659" },
  qml: { name: "QML", width: 27, color: "#44a51c" },
  "qt script": { name: "Qt Script", width: 52, color: "#00b841" },
  quake: { name: "Quake", width: 37, color: "#882233" },
  quickbasic: { name: "QuickBASIC", width: 71, color: "#008080" },
  r: { name: "R", width: 9, color: "#198ce7" },
  raml: { name: "RAML", width: 35, color: "#77d9fb" },
  rbs: { name: "RBS", width: 25, color: "#701516" },
  rdoc: { name: "RDoc", width: 32, color: "#701516" },
  rexx: { name: "REXX", width: 34, color: "#d90e09" },
  rmarkdown: { name: "RMarkdown", width: 68, color: "#198ce7" },
  ron: { name: "RON", width: 27, color: "#a62c00" },
  rpgle: { name: "RPGLE", width: 41, color: "#2bde21" },
  runoff: { name: "RUNOFF", width: 50, color: "#665a4e" },
  racket: { name: "Racket", width: 40, color: "#3c5caa" },
  ragel: { name: "Ragel", width: 33, color: "#9d5200" },
  raku: { name: "Raku", width: 29, color: "#0000fb" },
  rascal: { name: "Rascal", width: 39, color: "#fffaa0" },
  rescript: { name: "ReScript", width: 50, color: "#ed5051" },
  reason: { name: "Reason", width: 43, color: "#ff5847" },
  reasonligo: { name: "ReasonLIGO", width: 73, color: "#ff5847" },
  rebol: { name: "Rebol", width: 33, color: "#358a5b" },
  "record jar": { name: "Record Jar", width: 64, color: "#0673ba" },
  red: { name: "Red", width: 23, color: "#f50000" },
  "regular expression": { name: "Regular Expression", width: 113, color: "#009a00" },
  "ren'py": { name: "Ren'Py", width: 41, color: "#ff7f7f" },
  rez: { name: "Rez", width: 22, color: "#ffdab3" },
  ring: { name: "Ring", width: 27, color: "#2d54cb" },
  riot: { name: "Riot", width: 24, color: "#a71e49" },
  robotframework: { name: "RobotFramework", width: 99, color: "#00c0b5" },
  roc: { name: "Roc", width: 23, color: "#7c38f5" },
  roff: { name: "Roff", width: 25, color: "#ecdebe" },
  "roff manpage": { name: "Roff Manpage", width: 80, color: "#ecdebe" },
  rouge: { name: "Rouge", width: 38, color: "#cc0088" },
  "routeros script": { name: "RouterOS Script", width: 94, color: "#de3941" },
  ruby: { name: "Ruby", width: 30, color: "#701516" },
  rust: { name: "Rust", width: 28, color: "#dea584" },
  sas: { name: "SAS", width: 25, color: "#b34936" },
  scss: { name: "SCSS", width: 33, color: "#c6538c" },
  sparql: { name: "SPARQL", width: 50, color: "#0c4597" },
  sqf: { name: "SQF", width: 25, color: "#3f3f3f" },
  sql: { name: "SQL", width: 25, color: "#e38c00" },
  sqlpl: { name: "SQLPL", width: 41, color: "#e38c00" },
  "srecode template": { name: "SRecode Template", width: 107, color: "#348a34" },
  stl: { name: "STL", width: 23, color: "#373b5e" },
  svg: { name: "SVG", width: 25, color: "#ff9900" },
  saltstack: { name: "SaltStack", width: 54, color: "#646464" },
  sass: { name: "Sass", width: 28, color: "#a53b70" },
  scala: { name: "Scala", width: 32, color: "#c22d40" },
  scaml: { name: "Scaml", width: 35, color: "#bd181a" },
  scenic: { name: "Scenic", width: 39, color: "#fdc700" },
  scheme: { name: "Scheme", width: 46, color: "#1e4aec" },
  scilab: { name: "Scilab", width: 36, color: "#ca0f21" },
  self: { name: "Self", width: 23, color: "#0579aa" },
  shaderlab: { name: "ShaderLab", width: 63, color: "#222c37" },
  shell: { name: "Shell", width: 29, color: "#89e051" },
  "shellcheck config": { name: "ShellCheck Config", width: 106, color: "#cecfcb" },
  shen: { name: "Shen", width: 29, color: "#120f14" },
  "simple file verification": { name: "Simple File Verification", width: 131, color: "#c9bfed" },
  singularity: { name: "Singularity", width: 62, color: "#64e6ad" },
  slash: { name: "Slash", width: 32, color: "#007eff" },
  slice: { name: "Slice", width: 28, color: "#003fa2" },
  slim: { name: "Slim", width: 26, color: "#2b2b2b" },
  slint: { name: "Slint", width: 27, color: "#2379f4" },
  smpl: { name: "SmPL", width: 35, color: "#c94949" },
  smalltalk: { name: "Smalltalk", width: 53, color: "#596706" },
  smarty: { name: "Smarty", width: 41, color: "#f0c040" },
  smithy: { name: "Smithy", width: 40, color: "#c44536" },
  snakemake: { name: "Snakemake", width: 66, color: "#419179" },
  solidity: { name: "Solidity", width: 44, color: "#aa6746" },
  sourcepawn: { name: "SourcePawn", width: 72, color: "#f69e1d" },
  squirrel: { name: "Squirrel", width: 45, color: "#800000" },
  stan: { name: "Stan", width: 26, color: "#b2011d" },
  "standard ml": { name: "Standard ML", width: 73, color: "#dc566d" },
  starlark: { name: "Starlark", width: 45, color: "#76d275" },
  stata: { name: "Stata", width: 30, color: "#1a5f91" },
  stringtemplate: { name: "StringTemplate", width: 87, color: "#3fb34f" },
  stylus: { name: "Stylus", width: 36, color: "#ff6347" },
  "subrip text": { name: "SubRip Text", width: 70, color: "#9e0101" },
  sugarss: { name: "SugarSS", width: 50, color: "#2fcc9f" },
  supercollider: { name: "SuperCollider", width: 80, color: "#46390b" },
  "survex data": { name: "Survex data", width: 68, color: "#ffcc99" },
  svelte: { name: "Svelte", width: 36, color: "#ff3e00" },
  sway: { name: "Sway", width: 31, color: "#00f58c" },
  sweave: { name: "Sweave", width: 44, color: "#198ce7" },
  swift: { name: "Swift", width: 30, color: "#f05138" },
  systemverilog: { name: "SystemVerilog", width: 83, color: "#dae1c2" },
  "ti program": { name: "TI Program", width: 65, color: "#a0aa87" },
  "tl-verilog": { name: "TL-Verilog", width: 60, color: "#c40023" },
  tla: { name: "TLA", width: 25, color: "#4b0079" },
  toml: { name: "TOML", width: 35, color: "#9c4221" },
  tsql: { name: "TSQL", width: 34, color: "#e38c00" },
  tsv: { name: "TSV", width: 25, color: "#237346" },
  tsx: { name: "TSX", width: 25, color: "#3178c6" },
  txl: { name: "TXL", width: 24, color: "#0178b8" },
  tact: { name: "Tact", width: 26, color: "#48b5ff" },
  talon: { name: "Talon", width: 32, color: "#333333" },
  tcl: { name: "Tcl", width: 17, color: "#e4cc98" },
  tex: { name: "TeX", width: 23, color: "#3d6117" },
  terra: { name: "Terra", width: 30, color: "#00004c" },
  "terraform template": { name: "Terraform Template", width: 112, color: "#7b42bb" },
  textgrid: { name: "TextGrid", width: 49, color: "#c8506d" },
  "textmate properties": { name: "TextMate Properties", width: 115, color: "#df66e4" },
  textile: { name: "Textile", width: 38, color: "#ffe7ac" },
  thrift: { name: "Thrift", width: 33, color: "#d12127" },
  toit: { name: "Toit", width: 23, color: "#c2c9fb" },
  turing: { name: "Turing", width: 37, color: "#cf142b" },
  twig: { name: "Twig", width: 27, color: "#c1d026" },
  typescript: { name: "TypeScript", width: 63, color: "#3178c6" },
  typespec: { name: "TypeSpec", width: 57, color: "#4a3665" },
  typst: { name: "Typst", width: 33, color: "#239dad" },
  "unified parallel c": { name: "Unified Parallel C", width: 99, color: "#4e3617" },
  "unity3d asset": { name: "Unity3D Asset", width: 82, color: "#222c37" },
  uno: { name: "Uno", width: 24, color: "#9933cc" },
  unrealscript: { name: "UnrealScript", width: 72, color: "#a54c4d" },
  urweb: { name: "UrWeb", width: 39, color: "#ccccee" },
  v: { name: "V", width: 10, color: "#4f87c4" },
  vba: { name: "VBA", width: 27, color: "#867db1" },
  vbscript: { name: "VBScript", width: 53, color: "#15dcdc" },
  vcl: { name: "VCL", width: 26, color: "#148aa8" },
  vhdl: { name: "VHDL", width: 34, color: "#adb2cb" },
  vala: { name: "Vala", width: 25, color: "#a56de2" },
  "valve data format": { name: "Valve Data Format", width: 106, color: "#f26025" },
  "velocity template language": {
    name: "Velocity Template Language",
    width: 162,
    color: "#507cff",
  },
  verilog: { name: "Verilog", width: 41, color: "#b2b7f8" },
  "vim help file": { name: "Vim Help File", width: 76, color: "#199f4b" },
  "vim script": { name: "Vim Script", width: 61, color: "#199f4b" },
  "vim snippet": { name: "Vim Snippet", width: 71, color: "#199f4b" },
  "visual basic .net": { name: "Visual Basic .NET", width: 103, color: "#945db7" },
  "visual basic 6.0": { name: "Visual Basic 6.0", width: 92, color: "#2c6353" },
  volt: { name: "Volt", width: 24, color: "#1f1f1f" },
  vue: { name: "Vue", width: 23, color: "#41b883" },
  vyper: { name: "Vyper", width: 35, color: "#2980b9" },
  wdl: { name: "WDL", width: 29, color: "#42f1f4" },
  wgsl: { name: "WGSL", width: 38, color: "#1a5e9a" },
  "web ontology language": { name: "Web Ontology Language", width: 142, color: "#5b70bd" },
  webassembly: { name: "WebAssembly", width: 83, color: "#04133b" },
  "webassembly interface type": {
    name: "WebAssembly Interface Type",
    width: 167,
    color: "#6250e7",
  },
  whiley: { name: "Whiley", width: 40, color: "#d5c397" },
  wikitext: { name: "Wikitext", width: 48, color: "#fc5757" },
  "windows registry entries": { name: "Windows Registry Entries", width: 149, color: "#52d5ff" },
  "witcher script": { name: "Witcher Script", width: 83, color: "#ff0000" },
  wollok: { name: "Wollok", width: 40, color: "#a23738" },
  "world of warcraft addon data": {
    name: "World of Warcraft Addon Data",
    width: 172,
    color: "#f7e43f",
  },
  wren: { name: "Wren", width: 31, color: "#383838" },
  x10: { name: "X10", width: 23, color: "#4b6bef" },
  xc: { name: "XC", width: 18, color: "#99da07" },
  xml: { name: "XML", width: 27, color: "#0060ac" },
  "xml property list": { name: "XML Property List", width: 104, color: "#0060ac" },
  xquery: { name: "XQuery", width: 44, color: "#5232e7" },
  xslt: { name: "XSLT", width: 31, color: "#eb8ceb" },
  xmake: { name: "Xmake", width: 40, color: "#22a079" },
  xojo: { name: "Xojo", width: 28, color: "#81bd41" },
  xonsh: { name: "Xonsh", width: 38, color: "#285eef" },
  xtend: { name: "Xtend", width: 34, color: "#24255d" },
  yaml: { name: "YAML", width: 35, color: "#cb171e" },
  yara: { name: "YARA", width: 34, color: "#220000" },
  yasnippet: { name: "YASnippet", width: 62, color: "#32ab90" },
  yacc: { name: "Yacc", width: 29, color: "#4b6c4b" },
  yul: { name: "Yul", width: 19, color: "#794932" },
  zap: { name: "ZAP", width: 25, color: "#0d665e" },
  zil: { name: "ZIL", width: 20, color: "#dc75e5" },
  zenscript: { name: "ZenScript", width: 57, color: "#00bcd1" },
  zephir: { name: "Zephir", width: 39, color: "#118f9e" },
  zig: { name: "Zig", width: 19, color: "#ec915c" },
  zimpl: { name: "Zimpl", width: 33, color: "#d67711" },
  crontab: { name: "crontab", width: 45, color: "#ead7ac" },
  ec: { name: "eC", width: 16, color: "#913960" },
  fish: { name: "fish", width: 22, color: "#4aae47" },
  hoon: { name: "hoon", width: 29, color: "#00b171" },
  icalendar: { name: "iCalendar", width: 56, color: "#ec564c" },
  jq: { name: "jq", width: 12, color: "#c7254e" },
  kvlang: { name: "kvlang", width: 38, color: "#1da6e0" },
  "mirc script": { name: "mIRC Script", width: 70, color: "#3d57c3" },
  mcfunction: { name: "mcfunction", width: 65, color: "#e22837" },
  mdsvex: { name: "mdsvex", width: 45, color: "#5f9ea0" },
  mupad: { name: "mupad", width: 39, color: "#244963" },
  nanorc: { name: "nanorc", width: 40, color: "#2d004d" },
  nesc: { name: "nesC", width: 30, color: "#94b0c7" },
  ooc: { name: "ooc", width: 22, color: "#b0b77e" },
  q: { name: "q", width: 7, color: "#0040cd" },
  restructuredtext: { name: "reStructuredText", width: 97, color: "#141414" },
  sed: { name: "sed", width: 21, color: "#64b970" },
  templ: { name: "templ", width: 33, color: "#66d0dd" },
  vcard: { name: "vCard", width: 35, color: "#ee2647" },
  wisp: { name: "wisp", width: 28, color: "#7582d1" },
  xbase: { name: "xBase", width: 37, color: "#403a40" },
};

const longestLanguage = { name: "Cloud Firestore Security Rules", width: 176, color: "#ffa000" };

export { languages, longestLanguage };
